server:
  port: 8088

spring:
  application:
    name: OAuth2-Auth-Server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2demo?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 36000
      maximum-pool-size: 15
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

management:
  endpoint:
    health:
      enabled: true