server:
  port: 8090
  servlet:
    context-path: /code

spring:
  application:
    name: OAuth2-Auth-Code
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

security:
  oauth2:
    client:
      client-id: code-client
      client-secret: code_123456
      user-authorization-uri: http://localhost:8088/oauth/authorize
      access-token-uri: http://localhost:8088/oauth/token
    resource:
      id: code-client
      user-info-uri: code-info
    authorization:
      check-token-access: http://localhost:8088/oauth/check_token