server:
  port: 8089

spring:
  application:
    name: OAuth-User
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env